### ISSUE TITLE
Add script for playing tournaments between GTP players

### ISSUE THREAD

**Issue by dmorrill10** [ryanbhayward/games-puzzles-algorithms#65]
Ideally should integrate will all our games. Usage would be something like

`play-tournament -p <list of players> -g <game>`. E.g. 
```bash
game='ttt'
mcts="bin/gpa-games-cli -g $game -a mcts"
ab="bin/gpa-games-cli -g $game -a alpha-beta"
play-tournament -p [$mcts, $ab] -g $game
```

**Comment by JesseH-** [comment]
Is anyone looking at this? I'm going to be out of town and unreachable without internet access until Tuesday, so I can probably take a crack at this, as it seems rather self-contained.
